DROP TABLE IF EXISTS digimons, tamers CASCADE;

CREATE TABLE digimons (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image TEXT NOT NULL,
  series TEXT NOT NULL,
  level TEXT NOT NULL,
  attribute TEXT NOT NULL,
  type TEXT NOT NULL,
  can_digivolve BOOLEAN NOT NULL,
  tamer TEXT NOT NULL
);

CREATE TABLE tamers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  generation TEXT NOT NULL,
  partner BIGINT REFERENCES digimon(id),
  can_spiritvolve BOOLEAN NOT NULL,
  digivice TEXT NOT NULL
);